name: chatbot

services:
  llm_db:
    build:
      context: ./llm_generator/db_model
    container_name: llm_db
    restart: unless-stopped
    env_file:
      - ../../.env.docker
    environment:
      POSTGRES_USER: ${LLM_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LLM_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  llm_app:
    build:
      context: ./llm_generator
    container_name: llm_handler
    depends_on:
      - llm_db
    env_file:
      - .env.docker
    environment:
      ENV: production
      LLM_POSTGRES_HOST: llm_db
      LLM_POSTGRES_PORT: ${LLM_POSTGRES_PORT}
      LLM_POSTGRES_USERNAME: ${LLM_POSTGRES_USERNAME}
      LLM_POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      LLM_POSTGRES_DB: ${LLM_POSTGRES_DB}
    ports:
      - "8001:8001"  # Solo necesario si se accede desde fuera del contenedor
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  backend:
    build:
      context: ./backend  # Ajusta esto a la ruta de tu Dockerfile del backend
    container_name: backend
    depends_on:
      - llm_app
      - llm_db
    env_file:
      - db_sandoz/.env.docker
    environment:
      ENV: production
      LLM_APP_HOST: llm_app
      LLM_APP_PORT: ${LLM_APP_PORT}
      LLM_POSTGRES_HOST: llm_db
      LLM_POSTGRES_PORT: ${LLM_POSTGRES_PORT}
      LLM_POSTGRES_USERNAME: ${LLM_POSTGRES_USERNAME}
      LLM_POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      LLM_POSTGRES_DB: ${LLM_POSTGRES_DB}
    ports:
      - 8000:8000
      - 5678:5678

  postgres-external:
    container_name: chatbot-postgresql-external
    build:
      context: ./db_sandoz
    volumes:
      - postgres-external:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    command: -p 5435
    env_file:
      - db_sandoz/.env.docker

  pgadmin:
    container_name: chatbot-pgadmin
    image: dpage/pgadmin4:8.1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-local:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=chatbot@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456

volumes:
  postgres_data:
  postgres-external:
  pgadmin-local:

