services:
  llm_db:
    build:
      context: ./llm_generator/db_model
    container_name: llm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${LLM_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${LLM_POSTGRES_HOST}
      POSTGRES_PORT: ${LLM_POSTGRES_PORT}
      POSTGRES_DB: ${LLM_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    command: -p 5434

  llm_app:
    build:
      context: ./llm_generator
      args:
        GPU_TYPE: nvidia
    container_name: llm_handler
    depends_on:
      - llm_db
    environment:
      ENV: production
      POSTGRES_USER: ${LLM_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${LLM_POSTGRES_HOST}
      POSTGRES_PORT: ${LLM_POSTGRES_PORT}
      POSTGRES_DB: ${LLM_POSTGRES_DB}
      EXTERNAL_POSTGRES_USERNAME: ${EXTERNAL_POSTGRES_USERNAME}
      EXTERNAL_POSTGRES_PASSWORD: ${EXTERNAL_POSTGRES_PASSWORD}
      EXTERNAL_POSTGRES_HOST: ${EXTERNAL_POSTGRES_HOST}
      EXTERNAL_POSTGRES_PORT: ${EXTERNAL_POSTGRES_PORT}
      EXTERNAL_POSTGRES_DB: ${EXTERNAL_POSTGRES_DB}
    ports:
      - "5001:5001" # Solo necesario si se accede desde fuera del contenedor
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    container_name: chatbot-postgresql
    image: postgres:15.4
    volumes:
      - postgres-local:/var/lib/postgresql/data
    ports:
      - 5433:5433
    command: -p 5433
    env_file:
      - backend/.env.docker

  backend:
    container_name: backend
    platform: linux/x86_64
    build:
      context: ./backend
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/code
    env_file:
      - backend/.env.docker
    depends_on:
      - postgres

  postgres-external:
    container_name: chatbot-postgresql-external
    build:
      context: ./db_sandoz
    volumes:
      - postgres-external:/var/lib/postgresql/data
    ports:
      - 5435:5432
    command: -p 5435
    environment:
      POSTGRES_USER: ${EXTERNAL_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${EXTERNAL_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${EXTERNAL_POSTGRES_HOST}
      POSTGRES_PORT: ${EXTERNAL_POSTGRES_PORT}
      POSTGRES_DB: ${EXTERNAL_POSTGRES_DB}

  pgadmin:
    container_name: chatbot-pgadmin
    image: dpage/pgadmin4:8.1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-local:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=chatbot@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456

volumes:
  postgres_data:
  pgadmin-local:
    external: true
  postgres-local:
    external: true
  postgres-external:
    external: true