"""populate tables

Revision ID: 20250201092000
Revises: 20250201091937
Create Date: 2025-02-01 10:00:45.801059

"""

from alembic import op
import sqlalchemy as sa
import pandas as pd

# revision identifiers, used by Alembic.
revision = "20250201092000"
down_revision = "20250201091937"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    file_path = "src/migrations/resources/dataset.xlsx"
    xlsx = pd.ExcelFile(file_path)

    df = pd.read_excel(xlsx, "MARKET MAPPING", keep_default_na=False)

    market_mapping_data = df.to_dict(orient="records")

    op.bulk_insert(
        sa.table(
            "market_mapping",
            sa.column("market", sa.String),
            sa.column("market_des", sa.String),
            sa.column("cluster", sa.String),
            sa.column("region", sa.String),
        ),
        market_mapping_data
    )

    df = pd.read_excel(xlsx, "MONTHLY_BALANCE", dtype={"month": str})
    monthly_balance_data = df.to_dict(orient="records")

    op.bulk_insert(
        sa.table(
            "monthly_balance",
            sa.column("month", sa.String),
            sa.column("market", sa.String),
            sa.column("bu", sa.String),
            sa.column("volume", sa.Numeric),
            sa.column("value", sa.Numeric),
        ),
        monthly_balance_data
    )

    df = pd.read_excel(xlsx, "MONTHLY_LO", dtype={"month": str})
    monthly_lo_data = df.to_dict(orient="records")

    op.bulk_insert(
        sa.table(
            "monthly_lo",
            sa.column("month", sa.String),
            sa.column("market", sa.String),
            sa.column("bu", sa.String),
            sa.column("value", sa.Numeric),
        ),
        monthly_lo_data
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
