"""create monthly lo

Revision ID: 20250129215102
Revises: 20250129213528
Create Date: 2025-01-29 22:51:02.911599

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250129215102"
down_revision = "20250129213528"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monthly_lo",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("month", sa.String(6), nullable=False),
        sa.Column("market", sa.String(length=2), nullable=False),
        sa.Column("bu", sa.String(length=16), nullable=False),
        sa.Column("value", sa.NUMERIC(precision=20, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monthly_lo_bu"), "monthly_lo", ["bu"], unique=False)
    op.create_index(op.f("ix_monthly_lo_created_at"), "monthly_lo", ["created_at"], unique=False)
    op.create_index(op.f("ix_monthly_lo_market"), "monthly_lo", ["market"], unique=False)
    op.create_index(op.f("ix_monthly_lo_month"), "monthly_lo", ["month"], unique=False)
    op.create_index(op.f("ix_monthly_lo_value"), "monthly_lo", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monthly_lo_value"), table_name="monthly_lo")
    op.drop_index(op.f("ix_monthly_lo_month"), table_name="monthly_lo")
    op.drop_index(op.f("ix_monthly_lo_market"), table_name="monthly_lo")
    op.drop_index(op.f("ix_monthly_lo_created_at"), table_name="monthly_lo")
    op.drop_index(op.f("ix_monthly_lo_bu"), table_name="monthly_lo")
    op.drop_table("monthly_lo")
    # ### end Alembic commands ###
