"""create chat

Revision ID: 20250201222904
Revises:
Create Date: 2025-02-01 23:29:06.524019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250201222904"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_id"), "chat", ["id"], unique=False)
    op.create_index(op.f("ix_chat_created_at"), "chat", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_created_at"), table_name="chat")
    op.drop_index(op.f("ix_chat_id"), table_name="chat")
    op.drop_table("chat")
    # ### end Alembic commands ###
