"""create market mapping

Revision ID: 20250129213415
Revises:
Create Date: 2025-01-29 22:34:16.740477

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250129213415"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_mapping",
        sa.Column("market", sa.String(length=2), nullable=False),
        sa.Column("market_des", sa.String(length=32), nullable=False),
        sa.Column("cluster", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("market"),
    )
    op.create_index(op.f("ix_market_mapping_cluster"), "market_mapping", ["cluster"], unique=False)
    op.create_index(op.f("ix_market_mapping_created_at"), "market_mapping", ["created_at"], unique=False)
    op.create_index(op.f("ix_market_mapping_market_des"), "market_mapping", ["market_des"], unique=False)
    op.create_index(op.f("ix_market_mapping_region"), "market_mapping", ["region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_mapping_region"), table_name="market_mapping")
    op.drop_index(op.f("ix_market_mapping_market_des"), table_name="market_mapping")
    op.drop_index(op.f("ix_market_mapping_created_at"), table_name="market_mapping")
    op.drop_index(op.f("ix_market_mapping_cluster"), table_name="market_mapping")
    op.drop_table("market_mapping")
    # ### end Alembic commands ###
