"""create chat

Revision ID: 20250201122552
Revises: 20250201092000
Create Date: 2025-02-01 13:25:54.768330

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250201122552"
down_revision = "20250201092000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.drop_column("chat", "status")
    op.drop_column("chat", "question")
    op.drop_column("chat", "answer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("answer", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("chat", sa.Column("question", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column(
        "chat",
        sa.Column(
            "status", sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("chat", "owner_id")
    # ### end Alembic commands ###
