"""create chat message

Revision ID: 20250201222930
Revises: 20250201222904
Create Date: 2025-02-01 23:29:32.266385

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20250201222930"
down_revision = "20250201222904"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("llm_response_id", sa.UUID(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("query_explanation", sa.Text(), nullable=True),
        sa.Column("query_response", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_message_created_at"), "chat_message", ["created_at"], unique=False)
    op.create_index(op.f("ix_chat_message_is_valid"), "chat_message", ["is_valid"], unique=False)
    op.create_index(op.f("ix_chat_message_status"), "chat_message", ["status"], unique=False)
    op.create_index(op.f("ix_chat_message_llm_response_id"), "chat_message", ["llm_response_id"], unique=False)
    op.create_index(op.f("ix_chat_message_chat_id"), "chat_message", ["chat_id"], unique=False)
    op.create_index(op.f("ix_chat_message_id"), "chat_message", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_message_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_chat_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_llm_response_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_status"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_is_valid"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_created_at"), table_name="chat_message")
    op.drop_table("chat_message")
    # ### end Alembic commands ###
