version: "3.9"
services:
  llm_db:
    build:
      context: ./db_model
      dockerfile: Dockerfile
    container_name: llm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${LLM_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LLM_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  app:
    build: .
    container_name: llm_handler
    depends_on:
      - llm_db
    environment:
      # Configuración para la conexión interna a la DB (dentro de Docker)
      ENV: production
      LLM_POSTGRES_HOST: llm_db
      LLM_POSTGRES_PORT: ${LLM_POSTGRES_PORT}
      LLM_POSTGRES_USERNAME: ${LLM_POSTGRES_USERNAME}
      LLM_POSTGRES_PASSWORD: ${LLM_POSTGRES_PASSWORD}
      LLM_POSTGRES_DB: ${LLM_POSTGRES_DB}
      
      # Si se requiere la conexión externa, también puedes definirla:
      #EXTERNAL_POSTGRES_HOST: ${EXTERNAL_POSTGRES_HOST}
      #EXTERNAL_POSTGRES_PORT: ${EXTERNAL_POSTGRES_PORT}
      #EXTERNAL_POSTGRES_USERNAME: ${EXTERNAL_POSTGRES_USERNAME}
      #EXTERNAL_POSTGRES_PASSWORD: ${EXTERNAL_POSTGRES_PASSWORD}
      #EXTERNAL_POSTGRES_DB: ${EXTERNAL_POSTGRES_DB}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
